# VAE Training Configuration
batch_size: 32
learning_rate: 0.001
num_epochs: 100
device: "cuda"
seed: 42
save_interval: 10
log_interval: 100
checkpoint_dir: "checkpoints/vae"
log_dir: "logs/vae"
data_dir: "data/images"

# VAE-specific parameters
latent_dim: 20
image_size: 64
channels: 3
hidden_dims: [32, 64, 128, 256, 512]
kl_weight: 1.0
reconstruction_loss: "mse"

# KL annealing parameters
kl_annealing: true
kl_annealing_epochs: 50